### ISSUE TITLE
Command Line YAML configuration has moved

### ISSUE THREAD

**Issue by pickeringar** [lowprize/homeassistant-solax-api#2]
As of release 2023.6, a change has been introduced for "command_line"
I have included the CPU temperature script as below in sensors.yaml before the Solax API code,
```
###############################################################################
# From: https://www.home-assistant.io/integrations/sensor.command_line        #
###############################################################################

# Example configuration.yaml entry
  command_line:
    - sensor:
        name: CPU Temperature
        command: "cat /sys/class/thermal/thermal_zone0/temp"
# If errors occur, make sure configuration file is encoded as UTF-8
        unit_of_measurement: "°C"
        value_template: "{{ value | multiply(0.001) | round(1) }}"
```
but the File Editor is now complaining about "platform:rest"
```
- platform: rest
  name: Solax API
  resource: !secret solax_api
  method: GET
  scan_interval: 30
  value_template: "OK"
  json_attributes:
    - success
    - exception
    - result
```
Does the original YAML need updating to comply with this change?
